CREATE TYPE user_role AS ENUM ('ADMIN','EDITOR','VIEWER');
CREATE TYPE doc_status AS ENUM ('ACTIVE','DELETED');
CREATE TYPE perm_level AS ENUM ('VIEW','EDIT');
CREATE TYPE job_status AS ENUM ('QUEUED','RUNNING','SUCCESS','FAILED');
CREATE TYPE audit_action AS ENUM ('LOGIN','UPLOAD','NEW_VERSION','UPDATE_META','ADD_TAG','REMOVE_TAG','MOVE_FOLDER','SHARE','UNSHARE','DELETE','RESTORE','DOWNLOAD');
CREATE TYPE job_type AS ENUM ('INDEX_TEXT');
